apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
 reverse_proxy.conf: |
    server {
        listen 80;
        server_name netflix.mahe.my.id;

        location / {
            proxy_pass http://netflix-app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
