apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: mahesaj/netflix:v.1000
        ports:
        - containerPort: 3000


#apiVersion: v1
#kind: Service
#metadata:
#  name: netflix-app
#  labels:
#    app: netflix-app
#spec:
#  type: NodePort
#  ports:
#  - port: 3000
#    targetPort: 3000
#    nodePort: 30007
#  selector:
#    app: netflix-app
